import yfinance as yf
import pandas as pd
from sklearn.ensemble import RandomForestRegressor
from datetime import date, timedelta
from textblob import TextBlob
import feedparser
import numpy as np
import requests
import os

# --- 1. SETTINGS (GitHub Secrets-la irunthu edukum) ---
# Idhu mukkiyam: Code-la token irukka koodathu.
MY_BOT_TOKEN = os.environ.get("MY_BOT_TOKEN")
MY_CHANNEL_NAME = os.environ.get("MY_CHANNEL_NAME")
YEARS = 2

print("🤖 Cloud Bot Starting...")

# --- 2. TELEGRAM FUNCTION ---
def send_telegram_alert(message):
    if not MY_BOT_TOKEN or not MY_CHANNEL_NAME:
        print("❌ Error: Token or Channel Name not found in Secrets!")
        return

    try:
        url = f"https://api.telegram.org/bot{MY_BOT_TOKEN}/sendMessage"
        params = {"chat_id": MY_CHANNEL_NAME, "text": message, "parse_mode": "Markdown"}
        resp = requests.get(url, params=params, timeout=10)
        
        if resp.status_code == 200:
            print("✅ Telegram Message Sent Successfully!")
        else:
            print(f"❌ Telegram Error: {resp.text}")
    except Exception as e:
        print(f"⚠️ Network Error: {e}")

# --- 3. FETCH DATA ---
print("📊 Fetching Gold Data...")
today = date.today().strftime("%Y-%m-%d")
start_date = (date.today() - timedelta(days=YEARS*365)).strftime("%Y-%m-%d")

try:
    gold = yf.download('GC=F', start=start_date, end=today, progress=False)
    silver = yf.download('SI=F', start=start_date, end=today, progress=False)
    oil = yf.download('CL=F', start=start_date, end=today, progress=False)

    def clean(df):
        if df.empty: return pd.DataFrame()
        if isinstance(df.columns, pd.MultiIndex): df = df.xs('Close', axis=1, level=0)
        else: df = df[['Close']] if 'Close' in df.columns else df.iloc[:, 0].to_frame()
        return df

    df = pd.concat([clean(gold), clean(silver), clean(oil)], axis=1)
    df.columns = ['Gold', 'Silver', 'Oil']
    df.ffill(inplace=True)
    df['SMA_15'] = df['Gold'].rolling(window=15).mean()
    df.dropna(inplace=True)

    if len(df) < 50:
        print("❌ Not enough data to predict.")
        exit()

    # --- 4. AI TRAINING ---
    print("🧠 Training AI Model...")
    df['Target'] = df['Gold'].shift(-1)
    df.dropna(inplace=True)

    X = df[['Gold', 'Silver', 'Oil', 'SMA_15']].values
    y = df['Target'].values

    model = RandomForestRegressor(n_estimators=100, random_state=42)
    model.fit(X, y)

    last_row = df.iloc[-1]
    last_vals = np.array([[last_row['Gold'], last_row['Silver'], last_row['Oil'], last_row['SMA_15']]])
    pred_usd = model.predict(last_vals)[0]
    trend_pct = (pred_usd - last_row['Gold']) / last_row['Gold']

    # --- 5. NEWS ANALYSIS ---
    avg_sentiment = 0
    try:
        feed = feedparser.parse("https://news.google.com/rss/search?q=Gold+Price+Market+Trends&hl=en-IN&gl=IN&ceid=IN:en")
        sentiments = [TextBlob(e.title).sentiment.polarity for e in feed.entries[:5]]
        if sentiments: avg_sentiment = np.mean(sentiments)
    except: pass

    # --- 6. DECISION LOGIC ---
    total_change = trend_pct + (0.002 if avg_sentiment > 0.1 else -0.002 if avg_sentiment < -0.1 else 0)
    
    # Calculate Price (Approx INR)
    try: usdinr = yf.download('INR=X', period='1d', progress=False)['Close'].iloc[-1].item()
    except: usdinr = 86.50
    
    price_today = ((last_row['Gold'] * usdinr) / 31.1035) * 1.092 # +9.2% Tax
    price_tomorrow = price_today * (1 + total_change)

    if total_change > 0.001:
        signal, icon, advice = "BUY", "🟢", "Strong Upside! Accumulate."
    elif total_change < -0.001:
        signal, icon, advice = "SELL", "🔴", "Prices dropping. Wait."
    else:
        signal, icon, advice = "HOLD", "🟠", "Market Stable."

    # --- 7. SEND ALERT ---
    print(f"🎯 Signal Detected: {signal}")
    
    msg = f"""
🏆 *Ajay Gold Daily Auto-Report* 🏆

📅 *Signal:* {icon} *{signal}*
💰 *Price Prediction:* ₹{price_tomorrow:.2f}
📉 *Advice:* {advice}

_Generated by Cloud AI ☁️_
"""
    send_telegram_alert(msg)
    print("👋 Task Completed!")

except Exception as e:
    print(f"❌ Fatal Error: {e}")
